// <auto-generated />
#nullable enable
namespace BepInEx
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    [global::System.Diagnostics.Conditional("CodeGeneration")]
    internal sealed class BepInAutoPluginAttribute : global::System.Attribute
    {
        public BepInAutoPluginAttribute(string? id = null, string? name = null, string? version = null) {}
    }
}

namespace BepInEx.Preloader.Core.Patching
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    [global::System.Diagnostics.Conditional("CodeGeneration")]
    internal sealed class PatcherAutoPluginAttribute : global::System.Attribute
    {
        public PatcherAutoPluginAttribute(string? id = null, string? name = null, string? version = null) {}
    }
}