// <auto-generated />
namespace FsmMaster
{
    [global::BepInEx.BepInPlugin(FsmMasterPlugin.Id, "FsmMaster", "0.3.5")]
    partial class FsmMasterPlugin
    {
        /// <summary>
        /// The Id of <see cref="FsmMasterPlugin"/>.
        /// </summary>
        public const string Id = "io.github.constructivecynicism.fsmmaster";

        /// <summary>
        /// Gets the name of <see cref="FsmMasterPlugin"/>.
        /// </summary>
        public static string Name => "FsmMaster";

        /// <summary>
        /// Gets the version of <see cref="FsmMasterPlugin"/>.
        /// </summary>
        public static string Version => "0.3.5";
    }
}
